#---
# MODULE: EMBEDS
#---

[params.embeds]
imageDir = "assets/images/remote"
jsDir = "assets/js"
cssDir = "assets/css"

[params.embeds.youtube]
showCaptions = true
class = "js-only"

[params.embeds.tenor]
useVideo = true

# ⚠ API Keys ⚠
# Move these to a separate, gitignored file. See README for help.
[params.embeds.api]
itch = "" 						# For itch.io widget - @link https://itch.io/api-keys
logodev = "" 					# For generic site favicons
spotifyAccess = ""

[module.hugoVersion]
extended = true
min = "0.141.0"