#---
# MODULE: Search
#---
[params.search]
placeholder = "Search the site..."
page = "search"

# https://gohugo.io/getting-started/configuration/#_404-server-error-page
[server]
[[redirects]]
from = "/**"
to = "/404.html"
status = 404
