[outputFormats]
[outputFormats.RSS]
	mediatype = "application/rss"
	baseName = "feed"
# [outputFormats.feed_style]
#  	baseName = "feed-style"
#  	isPlainText = true
#  	mediaType = "text/xsl"
#  	notAlternative = true

# [mediaTypes]
# 	[mediaTypes."text/xsl"]
# 	suffixes = ['xsl']

# [outputs]
# home = [ "HTML", "RSS", "feed_style"]
