#---
# MODULE: SEO
#---

[params.author]
name = "Author"

[params.seo]
isPrivate = false # Hide site from search engines
noAI = true				# Attempt to block AI scraping

titleSeparator = " | "
OGSite = "" 							# Used for OG:Site
#OGCover = ""
UseCustomCovers = true

# https://moz.com/learn/seo/title-tag
maxTitleChars = 60
# https://www.authorityhacker.com/headlines/#longer-headlines-perform-better
maxOGTitleChars = 70
# https://yoast.com/meta-descriptions/
maxDescChars = 155
# https://ogtester.com/blog/what-is-maximum-length-of-og-title-and-og-description
maxOGDescChars = 85

useSchema = true				# Output JSON-LD schema
siteAlternateName = ""	# For certain Google JSON-LD schema
searchPageLayout = ""		# Layout used for your search page if any. Used for JSON-LD
paywallClass = ""				# CSS class name (with the dot) containing paywalled content.
themeColor = "#fff"				# Browser toolbar color
#themeColorDark = "#000"	# Browser toolbar color with dark OS theme
backgroundColor = "#fff"	# Browser fill color when PWA loads
#faviconPath = "favicon/"

[outputs]
home = [ "HTML", "RSS", "webappmanifest", "ai", "humans"]

[outputFormats]
[outputFormats.browserconfig]
	name = "browserconfig"
	baseName = "browserconfig"
	mediaType = "application/xml"
	notAlternative = true
[outputFormats.ai]
	baseName = "ai"
	mediaType = "text/plain"
	notAlternative = true
  isPlainText = true
[outputFormats.humans]
  baseName = "humans"
  mediaType = "text/plain"
	notAlternative = true
  isPlainText = true
