#---
# MODULE: SEO
#---

[params.author]
name = "Author"

[params.seo]
isPrivate = false # Hide site from search engines

titleSeparator = " | "
OGSite = "" 							# Used for OG:Site
#OGCover = ""

paginate = false # Whether your site uses pagination
paginateHome = false # Whether homepage uses pagination (if `paginate` is true)

# https://moz.com/learn/seo/title-tag
maxTitleChars = 60
# https://www.authorityhacker.com/headlines/#longer-headlines-perform-better
maxOGTitleChars = 70
# https://yoast.com/meta-descriptions/
maxDescChars = 155
# https://ogtester.com/blog/what-is-maximum-length-of-og-title-and-og-description
maxOGDescChars = 85

siteAlternateName = ""	# For certain Google JSON-LD schema. Can also be a slice
searchPageLayout = ""		# Layout used for your search page if any. Used for JSON-LD
paywallClass = ""				# CSS class name (with the dot) containing paywalled content.
themeColor = "#fff"				# Browser toolbar color
#themeColorDark = "#000"	# Browser toolbar color with dark OS theme
colorScheme = "light" # color-scheme CSS/meta tag value

faviconPath = "favicons/"

# --- Web Manifest
wmStartPage = "" # Start page
#wmShortName = ""
faviconWMGlob = "**web-app-manifest-*.png" #"**android-chrome*.png"
backgroundColor = "#fff"	# Browser fill color when PWA loads
wmDisplay = "standalone" # Webappmanifest display mode

[params.seo.OGCoverTemplate]
enabled = true
image = ""
size = "1200x630"
imageDir = "assets/images/covers"

[params.seo.ai]
block = true
whitelist = []
# Use `nocache` over `noarchive`, allowing Microsoft AI to use page title, snippet, and link, but not content
# @link https://www.bing.com/webmasters/help/which-robots-metatags-does-bing-support-5198d240
# @link https://blogs.bing.com/webmaster/september-2023/Announcing-new-options-for-webmasters-to-control-usage-of-their-content-in-Bing-Chat
bingAllowSnippet = false

[outputs]
home = [ "HTML", "RSS", "webappmanifest", "ai", "humans"]

[outputFormats]
# @NOTE webappmanifest is built into Hugo
[outputFormats.browserconfig]
	name = "browserconfig"
	baseName = "browserconfig"
	mediaType = "application/xml"
	notAlternative = true
[outputFormats.ai]
	baseName = "ai"
	mediaType = "text/plain"
	notAlternative = true
  isPlainText = true
[outputFormats.humans]
  baseName = "humans"
  mediaType = "text/plain"
	notAlternative = true
  isPlainText = true

[module.hugoVersion]
	extended = true
	min = "0.141.0"

[module]
[[module.imports]]
	path = "github.com/plasterbrain/hugo-modules/internals"