#---
# MODULE: PATREON_AUTH0
#---

[params.patreon]
campaignID = "" # https://www.patreon.com/api/campaigns/{ID}

[params.auth0]
domain = ""
client = ""

[outputFormats]
[outputFormats.auth_config]
	name = "auth_config"
	baseName = "auth_config"
	mediaType = "application/json"
	notAlternative = "true"

[outputs]
home = [ "HTML", "RSS", "auth_config"]
