#---
# MODULE: Images
#---

[params.images]
pathPrefix = "assets"
jsDir = "assets/js"

[params.images.icons]
path = "assets/images/%s.svg"

[module]
[[module.imports]]
	path = "github.com/plasterbrain/hugo-modules/internals"